#!/bin/bash
set -e # Exit immediately if a command exits with a non-zero status

chmod 755 /usr/local/bin/tpp/prereq.sh
chmod 755 /usr/local/bin/tpp/app.py
# Create necessary directories and set permissions
mkdir -p /var/log/tpp
chmod 755 /var/log/tpp

# Uncomment the line below to open a specific port if needed
sudo ufw allow 8080/tcp


# Enable and start the service
systemctl enable tpp.service
systemctl start tpp.service
